spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-init-sql: SET search_path TO batch_meta, app, public

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: app

  batch:
    jdbc:
      initialize-schema: always
      table-prefix: batch_meta.BATCH_
    job:
      enabled: true

logging:
  level:
    io.micrometer.cloudwatch2: info
    org.springframework.jdbc.datasource.init: info

    # SQL
    org.hibernate.sql: info # 실행된 SQL
    org.hibernate.orm.jdbc.bind: info # 바인딩 파라미터
    root: info
